### ISSUE TITLE
登录后去拿login信息时失败

### ISSUE THREAD

**Issue by dennis-ji** [tencentyun/wafer2-quickstart-nodejs#19]
![image](https://user-images.githubusercontent.com/34324933/42922427-151883fe-8b53-11e8-9c83-5f13f2a2f15c.png)

11:23:27.482 response.js:20 Catch Error: Error: ERR_SKEY_INVALID
    at validation (/data/release/node-weapp-demo/node_modules/wafer-node-sdk/lib/auth/index.js:91:22)
    at validationMiddleware (/data/release/node-weapp-demo/node_modules/wafer-node-sdk/lib/auth/index.js:139:12)
    at dispatch (/data/release/node-weapp-demo/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/data/release/node-weapp-demo/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /data/release/node-weapp-demo/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/data/release/node-weapp-demo/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /data/release/node-weapp-demo/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/data/release/node-weapp-demo/node_modules/koa-router/lib/router.js:351:31)
    at dispatch (/data/release/node-weapp-demo/node_modules/koa-compose/index.js:42:32)
    at parseBody.then.body (/data/release/node-weapp-demo/node_modules/koa-bodyparser/index.js:74:14)
    at <anonymous>

**Comment by jas0ncn** [comment]
是怎么请求的呢？

**Comment by dennis-ji** [comment]
使用wx.uploadFile请求的。
x-wx-key没有在header里。

**Comment by jas0ncn** [comment]
https://github.com/tencentyun/wafer2-client-sdk/issues/40
