### ISSUE TITLE
qcloud login Cannot read property 'skey' of null

### ISSUE THREAD

**Issue by kaiseu** [tencentyun/wafer2-quickstart-nodejs#8]
Cannot read property 'skey' of null;at pages/list page lifeCycleMethod onLoad function
TypeError: Cannot read property 'skey' of null
    at doRequest (http://127.0.0.1:52817/appservice/vendor/wafer2-client-sdk/lib/request.js:79:55)
    at Object.request (http://127.0.0.1:52817/appservice/vendor/wafer2-client-sdk/lib/request.js:69:9)
    at e.onLoad

**Comment by jas0ncn** [comment]
使用新的 qcloud.requestLogin 接口哈
